// packages/utilities/framer-utils/src/resizable-panel.tsx
import type { HTMLHeroUIProps } from "@veroui/system";
import type { Ref } from "react";

import { useMeasure } from "@veroui/composables";
import { domAnimation, LazyMotion, m } from "framer-motion";
import { forwardRef } from "react";

/**
 * Props for the ResizablePanel component.
 */
export interface ResizablePanelProps extends HTMLHeroUIProps<"div"> {}

const ResizablePanel = forwardRef((originalProps: ResizablePanelProps, ref: Ref<HTMLDivElement>) => {
    const { children, ...props } = originalProps;

    let [measureRef, bounds] = useMeasure();

    return (
        <LazyMotion features={domAnimation}>
            <m.div
                ref={ref}
                animate={{
                    width: bounds.width && bounds?.width > 0 ? bounds.width : "auto",
                    height: bounds.height && bounds.height > 0 ? bounds.height : "auto",
                }}
            >
                <div ref={measureRef} {...props}>
                    {children}
                </div>
            </m.div>
        </LazyMotion>
    );
});

ResizablePanel.displayName = "HeroUI - ResizablePanel";

export { ResizablePanel };

// packages/utilities/framer-utils/src/ResizablePanel.vue
<script lang="ts" setup>
import { useMeasure } from "@veroui/composables";
import { m, LazyMotion, domAnimation } from "motion-v";
import { ComponentInstance } from "vue";

const props = defineProps();
const parent = defineModel("parent");
const { elementRef, dimensions } = useMeasure();
</script>

<template>
    <LazyMotion :features="domAnimation as unknown as ComponentInstance<typeof LazyMotion>['$props']['features']">
        <m.div
            ref="parent"
            :animate="{
                width: dimensions.width && dimensions?.width > 0 ? dimensions.width : 'auto',
                height: dimensions.height && dimensions.height > 0 ? dimensions.height : 'auto',
            }"
        >
            <div ref="elementRef" v-bind="{ ...props } as {}">
                <slot />
            </div>
        </m.div>
    </LazyMotion>
</template>

<style scoped></style>
